### ISSUE TITLE
Issue while running 'npm install' on initial creation

### ISSUE THREAD

**Issue by aleworth** [JelteMX/generator-mendix-widget#3]
Whenever npm install is run (either after the initial yo mendix-widget command or doing it manually) I get an error at pngquant-bin@4.0.0 postinstall: 'node lib/install.js'. It says:
Failed at the pngquant-bin@4.0.0 postinstall script 'node lib/install.js'.

node.js and npm version:
3.5.2

**Comment by JelteMX** [comment]
What version of Node.js are you running?

**Comment by aleworth** [comment]
Sorry, forgot to include that in my initial post. Currently running version 8.10.0 of node.js

**Comment by JelteMX** [comment]
Hmmmm... I've used version 8 for a long time, but it isn't supported anymore (since 2019-01-01). See this [support schedule](https://github.com/nodejs/Release). My advice is to update to version 10.x. The modules for that (pngquant is used in Webpack) should be up to date for Node 10, I am using the same generator without any issue.

If that doesn't solve your problem, I'll have a look at possibly updating the dev-dependencies.
